var examples = [
	{
		name:'Wikipedia: basic tree',
		value:{
			seed:"0",
			rules:"1=11\n0=1[0]0",
			func:"1=line\n0=line\n[=push\n[=tl\n]=pop\n]=tr",
			iter:"7.0",
			len:"2.0",
			deg:"45.0",
			alpha:"1"
		}
	},
	{
		name:'Wikipedia: Koch curve',
		value:{
			seed:"F",
			rules:"F=F+F-F-F+F",
			func:"F=line\n+=tl\n-=tr",
			iter:"3.0",
			len:"5.0",
			deg:"90.0",
			alpha:"1"
		}
	},
	{
		name:'Wikipedia: Sierpinski triangle',
		value:{
			seed:"A",
			rules:"A=B-A-B\nB=A+B+A",
			func:"A=line\nB=line\n+=tl\n-=tr",
			iter:"7.0",
			len:"2.0",
			deg:"60.0",
			alpha:"1"
		}
	},
	{
		name:'Wikipedia: Dragon curve',
		value:{
			seed:"FX",
			rules:"X=X+YF\nY=FX-Y",
			func:"F=line\n+=tl\n-=tr",
			iter:"12.0",
			len:"4.0",
			deg:"90.0",
			alpha:"1"
		}
	},
	{
		name:'Wikipedia: Fractal plant',
		value:{
			seed:"X",
			rules:"F=FF\nX=F-[[X]+X]+F[+FX]-X",
			func:"F=line\n+=tl\n-=tr\n[=push\n]=pop",
			iter:"5.0",
			len:"4.0",
			deg:"25.0",
			alpha:"1"
		}
	},
	{
		name:'"City"',
		value:{
			seed:"[x][z]v",
			rules:"x=rAx\nv=rDv\nz=rWz\nA=a[z]A\nD=d[z]D\nW=wW",
			func:"r=rect\nw=mu\na=ml\ns=md\nd=mr\n[=push\n]=pop",
			iter:"15",
			len:"2",
			deg:"90",
			alpha:"0.4"
		}
	},
	{
		name:'Continents',
		value:{
			seed:"[x][z][c]e",
			rules:"x.6=xrw[D][A]zDc\nx.4=x\nz.6=zrs[D][A]eAx\nz.4=z\nc.6=crd[W][S]eWz\nc.4=c\ne.6=era[W]S[S]xc\ne.4=e\nD=Dd\nA=Aa\nW=Ww\nS=Ss",
			func:"r=rect\nw=mu\na=ml\ns=md\nd=mr\n[=push\n]=pop\n@=rep",
			iter:"12",
			len:"2",
			deg:"90",
			alpha:"0.2"
		}
	},
	{
		name:'Continents Base',
		value:{
			seed:"[x][z][c]e",
			rules:"x=xw[D][A]zDc\nz=zs[D][A]eAx\nc=cd[W][S]eWz\ne=ea[W]S[S]xc\nD=Ddr\nA=Aar\nW=Wwr\nS=Ssr",
			func:"r=rect\nw=mu\na=ml\ns=md\nd=mr\n[=push\n]=pop\n@=rep",
			iter:"6.0",
			len:"8",
			deg:"90",
			alpha:"0.2"
		}
	},
	{
		name:'Continents 2',
		value:{
			seed:"f",
			rules:"f.6=f[i]f\nf.1=Af\nf.1=Sf\nf.1=Wf\nf.1=Df\ni=[q][e][z]c\nq.2=a[e]r[z]q\nq.8=qa\ne.2=w[q]r[c]e\ne.8=ew\nz.2=s[q]r[c]z\nz.8=zs\nc.2=d[e]r[z]c\nc.8=cd\nD.4=Dd\nD.6=D\nA.4=Aa\nA.6=A\nW.4=Ww\nW.6=W\nS.4=Ss\nS.6=S",
			func:"r=rect\nw=mu\na=ml\ns=md\nd=mr\n[=push\n]=pop\n@=rep",
			iter:"20",
			len:"3",
			deg:"90",
			alpha:"0.2"
		}
	},
	{
		name:'"Mirorpinsky"',
		value:{
			seed:"0",
			rules:"1=11\n0=1[l0][0][r0]0",
			func:"1=line\n0=line\n[=push\n[=tl\n]=pop\n]=tr\nl=tl\nr=tr",
			iter:"8.0",
			len:"8.0",
			deg:"60.0",
			alpha:"1"
		}
	},
	{
		name:'Penrose!',
		value:{
			seed:"[N]++[N]++[N]++[N]++[N]",
			rules:"M=OA++PA----NA[-OA----MA]++\nN=+OA--PA[---MA--NA]+\nO=-MA++NA[+++OA++PA]-\nP=--OA++++MA[+PA++++NA]--NA\nA=",
			func:"A=line\n[=push\n-=tl\n]=pop\n+=tr",
			iter:"5.0",
			len:"16.0",
			deg:"36.0",
			alpha:"1"
		}
	},
	{
		name:'Crystal',
		value:{
			seed:"F+F+F+F",
			rules:"F=FF+F++F+F",
			func:"F=line\n+=tl",
			iter:"5.0",
			len:"2.0",
			deg:"90.0",
			alpha:"1"
		}
	},
	{
		name:'Random Crystal',
		value:{
			seed:"F+F+F+F",
			rules:"F.2=F+F++F+FFF\nF.2=FFF+F++F+F\nF.2=FF+F++F+FF\nF.2=FFF+FF++FF+F\nF.2=F+FF++FF+FFF",
			func:"F=line\n+=tr",
			iter:"4.0",
			len:"2.0",
			deg:"90.0",
			alpha:"1"
		}
	},
	{
		name:'Hex Crystal',
		value:{
			seed:"F+F+F+F+F+F",
			rules:"F=FF++FF+++FF+F+F+++F++F",
			func:"F=line\n+=tl",
			iter:"4.0",
			len:"2.0",
			deg:"60.0",
			alpha:"1"
		}
	},
	{
		name:'Islands',
		value:{
			seed:"F+F+F+F",
			rules:"F=F+f-FF+F+FF+Ff+FF-f+FF-F-FF-Ff-FFF\nf=ffffff",
			func:"F=line\nf=fwd\n-=tl\n+=tr",
			iter:"2.0",
			len:"5.0",
			deg:"90.0",
			alpha:"1"
		}
	}
];
